apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar
  labels:
    app: sonar
spec:
  selector:
    matchLabels:
      app: sonar
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: sonar
    spec:
      containers:
        - image: sonarqube:community
          imagePullPolicy: Always
          name: sonar
          ports:
            - containerPort: 9000